spring:
  data:
    rest:
      base-path: /api

space:
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiT1BUSUNORVRURVNUVjAiLCJpYXQiOjE2ODM2Nzc2NDksInN1YiI6ImFnZW50LXRva2VuIn0.fq3fC9MqEkUOTZdBzrX0CMGtaA4JEKlt2uO2CQ_yM-_hs3QKmbfWbUlTwfo4PRC1Iy4QkE4qIaHaad3kIiCqaVR07DIg-GN6tX2t2ffMLv26KAy6udMBRQBv31LhvNnknr-LrTLwEXJBhAug8ZhE5oZMDOEk0XD2wpnEGwNzRQRygo0nqAAwK9HHK6XhHudAzyBbUjrvKUFQMy-HjRpgbZLlXNXzn3Lop04osr89GrgnzdOoa-TilYzdpRh7xQO-qunzTaMKEx-ICMliv03DjAEaLdbARy6g6xenbIwwZ6MNt6eVuyt8TuZB08eq2NIVmt9KsNtvacud3pUTTiypKD4ekkwTjCuFVDj-7qwdgKY3nFsSJz-zJXM1sPncUXTHiQ736lZP5i9h66mXYpTfEI1A0zpGLEDIhnCbyZJm61GoUH8LN5h2ds2I7_7jqiuhiwyvgiUKn9ikBjsghVGEJr77ZQczIQi_n7FWM0_TtAGH909akLvuJyu61JMMIa_B